[build]
command = "hugo"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.119.0"
GO_VERSION = "1.21.3"

[context.branch-deploy.environment]
command = "hugo --buildDrafts --buildFuture"
HUGO_VERSION = "0.119.0"
GO_VERSION = "1.21.3"

[context.deploy-preview.environment]
command = "hugo --buildDrafts --buildFuture"
HUGO_VERSION = "0.119.0"
GO_VERSION = "1.21.3"
